variables:
  mysql_user: xyz
  mysql_password: xx
  mysql_db: db
  postgres_user: x
  postgres_password: x
  postgres_db: s
  sqlite_db: db
  solr_core_name: objective_love

core_lib:
  data:
    db:
      - protocol: mysql
        username: ${env:mysql_user}
        password: ${env:mysql_password}
        address: localhost
        port: 3306
        file: ${env:mysql_db}
      - protocol: sqlite
        file: ${env:sqlite_db}
      - protocol: postgres
        username: ${env:postgres_user}
        password: ${env:postgres_password}
        address: localhost
        port: 5432
        file: ${env:postgres_db}
    memcached:
      host: localhost
      port: 11211
    solr:
      protocol: http
      host: localhost
      port: 8983
      path: solr
      file: ${env:solr_core_name}

docker-compose:
version: '2'

services:

  core_lib_name:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
      solr:
        condition: service_healthy
      memcached:
        condition: service_healthy
    restart: always

  db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${mysql_root_password}
      MYSQL_DATABASE: ${mysql_db}
      MYSQL_USER: ${mysql_user}
      MYSQL_PASSWORD: ${mysql_password}