core_lib:
  app:
    secret: 000000000000000000101010110
  db:
    protocol: mysql
    username: test
    password: test
    host: localhost
    port: 3306
    file: test
    log_queries: False
    create_db: True
  solr:
    protocol: http
    host: localhost
    port: 8983
    file: solr/test
  memcached:
    host: localhost
    port: 11211